import os
import streamlit as st
from dotenv import load_dotenv

from langchain.chat_models import init_chat_model
from langchain_openai.embeddings import OpenAIEmbeddings 
from langchain_chroma import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

load_dotenv()

# Initialize embedding model
embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")

# Initialize company knowledge base
db = Chroma(collection_name="database",
            embedding_function=embedding_model,
            persist_directory='./knowledgebase')

def format_docs(docs):
    """Formats a list of document objects into a single string.

    Args:
        docs (list): A list of document objects, each having a 'page_content' attribute.

    Returns:
        str: A single string containing the page content from each document, 
        separated by double newlines."""
    return "\n\n".join(doc.page_content for doc in docs)

def add_to_db(uploaded_files):
    """Processes and adds uploaded PDF files to the database.

    This function checks if any files have been uploaded. If files are uploaded,
    it saves each file to a temporary location, processes the content using a PDF loader,
    and splits the content into smaller chunks. Each chunk, along with its metadata, 
    is then added to the database. Temporary files are removed after processing.

    Args:
        uploaded_files (list): A list of uploaded file objects to be processed.

    Returns:
        None"""
    # Check if files are uploaded
    if not uploaded_files:
        st.error("No files uploaded!")
        return

    for uploaded_file in uploaded_files:
        # Save the uploaded file to a temporary path
        temp_file_path = os.path.join("./temp", uploaded_file.name)
        os.makedirs(os.path.dirname(temp_file_path), exist_ok=True)

        with open(temp_file_path, "wb") as temp_file:
            temp_file.write(uploaded_file.getbuffer())

        # Load the file using PyPDFLoader
        loader = PyPDFLoader(temp_file_path)
        data = loader.load()

        # Store metadata and content
        doc_metadata = [data[i].metadata for i in range(len(data))]
        doc_content = [data[i].page_content for i in range(len(data))]

        # Split documents into smaller chunks
        st_text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
            encoding_name="cl100k_base",
            chunk_size=100,
            chunk_overlap=50
        )
        st_chunks = st_text_splitter.create_documents(doc_content, doc_metadata)

        # Add chunks to database
        db.add_documents(st_chunks)

        # Remove the temporary file after processing
        os.remove(temp_file_path)

def run_rag_chain(query):
    """Processes a query using a Retrieval-Augmented Generation (RAG) chain.

    This function utilizes a RAG chain to answer a given query. It retrieves 
    relevant context using similarity search and then generates a response 
    based on this context using a chat model. The chat model is pre-configured
    with a prompt template specialized in company policies and internal procedures.

    Args:
        query (str): The user's question that needs to be answered.

    Returns:
        str: A response generated by the chat model, based on the retrieved context."""
    # Create a Retriever Object and apply Similarity Search
    retriever = db.as_retriever(search_type="similarity", search_kwargs={'k': 5})

    # Initialize a Chat Prompt Template
    PROMPT_TEMPLATE = """
    You are a helpful internal company assistant.

    Answer employee questions using only the information provided in the company onboarding and internal documentation below.

    CONTEXT INFORMATION:
    {context}

    EMPLOYEE QUESTION:
    {question}

    INSTRUCTIONS:
    - Answer accurately, clearly, and concisely based only on the provided context.
    - Do not use outside knowledge or make assumptions.
    - Do not invent company policies, procedures, benefits, contacts, or other information.
    - If the answer cannot be found in the provided context, clearly say that you do not have enough information to answer the question.
    - Do not mention "the context," "provided documents," or similar phrases in your response.
    - Do not justify your answer unless the question specifically asks for an explanation.
    - Present steps, policies, or important details in a clear and easy-to-follow format when appropriate.
    - Maintain a professional, friendly, and helpful tone.

    ANSWER:
    """

    prompt_template = ChatPromptTemplate.from_template(PROMPT_TEMPLATE)

    # Initialize a Generator (i.e. Chat Model)
    chat_model = init_chat_model(
        model="gpt-4.1-mini",
        temperature=0.2
    )

    # Initialize a Output Parser
    output_parser = StrOutputParser()

    # RAG Chain
    rag_chain = {"context": retriever | format_docs, "question": RunnablePassthrough()} | prompt_template | chat_model | output_parser

    # Invoke the Chain
    response = rag_chain.invoke(query)

    return response

def main():
    """Initialize and manage EmployeeQuery application interface.

    This function sets up the Streamlit application interface for EmployeeQuery,
    a company policy assistant. Users can ask questions about company policies,
    upload internal policy documents, and manage API keys for the assistant.

    The main features include:
    - Query input area for users to ask questions about company policies.
    - Submission button to process the query and display the retrieved insights.
    - Sidebar for API key input and management.
    - File uploader for adding internal policy documents to the database.

    Args:
        None

    Returns:
        None"""
    st.set_page_config(page_title="Company Policy Assistant", page_icon=":office:")
    st.header("Company Policy Assistant")

    with st.form(key="rag_form"):
        query = st.text_area(
            "Ask a question about company policies",
            placeholder="e.g., How many vacation days do employees receive?"
        )
        
        # Form submit button (submits on click or Control + Enter in text_area)
        submit_button = st.form_submit_button(label="Submit")

    if submit_button:
        if not query:
            st.warning("Please ask a question")
        
        else:
            with st.spinner("Thinking..."):
                result = run_rag_chain(query=query)
                st.write(result)
    
    with st.sidebar:
        pdf_docs = st.file_uploader("Upload internal company policy documents (optional)",
                                    type=["pdf"],
                                    accept_multiple_files=True
        )
        
        if st.button("Submit & Process"):
            if not pdf_docs:
                st.warning("Please upload the file")

            else:
                with st.spinner("Processing your documents..."):
                    add_to_db(pdf_docs)
                    st.success(":file_folder: Documents successfully added to the database!")

             
if __name__ == "__main__":
    main()